USE BOOK1;
CREATE TABLE EMPDETAILS(
ID1 INT,
NAME1 VARCHAR(89),
SALARY int
);

CREATE TABLE EMPSTATUS(
ID2 INT,
NAME2 VARCHAR(89),
STATUSS VARCHAR(56)
);

INSERT INTO EMPDETAILS VALUES(1,"NANDU",45000),(2,"VISHU",52000),(3,"JETTI",23000);
INSERT INTO EMPSTATUS VALUES(1,"NANDU","UNMARRIED"),(2,"VISHU","MARRIED"),(4,"JETTI","MARRIED");
SELECT * FROM EMPDETAILS;
SELECT * FROM EMPSTATUS;
-- INNER JOIN 
SELECT ID1,NAME1,SALARY,STATUSS FROM EMPDETAILS INNER JOIN EMPSTATUS
ON EMPDETAILS.ID1=EMPSTATUS.ID2;


-- LEFT JOIN 

SELECT ID1,NAME1,SALARY ,STATUSS FROM EMPDETAILS LEFT JOIN EMPSTATUS ON EMPDETAILS.ID1=EMPSTATUS.ID2;

-- RIGHT JOIN

SELECT ID1,NAME1,SALARY ,STATUSS FROM EMPDETAILS RIGHT JOIN EMPSTATUS ON EMPDETAILS.ID1=EMPSTATUS.ID2;

-- OUTER JOIN

SELECT ID1,NAME1,SALARY ,STATUSS FROM EMPDETAILS LEFT JOIN EMPSTATUS ON EMPDETAILS.ID1=EMPSTATUS.ID2 UNION 
SELECT ID1,NAME1,SALARY ,STATUSS FROM EMPDETAILS RIGHT JOIN EMPSTATUS ON EMPDETAILS.ID1=EMPSTATUS.ID2;


-- SELF JOIN 
CREATE TABLE HAPPY(
COLOR1 VARCHAR(78),
NAMEE VARCHAR(78),
COLOR2 VARCHAR(67)
);
INSERT INTO HAPPY VALUES("BLUE","JOHN","RED"),("GREEN","ALEX","BLUE"),("RED","SIMON","GREEN");
SELECT * FROM HAPPY;
SELECT B.NAMEE,A.NAMEE FROM HAPPY AS A, HAPPY AS B WHERE A.COLOR1=B.COLOR2;

-- CROSS JOIN 

CREATE TABLE HAIR_TYPE(
TYPEE VARCHAR(89)
);
INSERT INTO HAIR_TYPE VALUES("A"),("B"),("C");
CREATE TABLE HAIR_STYLE(
TYPEE VARCHAR(67)
);
INSERT INTO HAIR_STYLE VALUES("STRAIGHT"),("CURLY"),("MODERN");
SELECT * FROM HAIR_TYPE;
SELECT * FROM HAIR_STYLE;

SELECT * FROM HAIR_TYPE CROSS JOIN HAIR_STYLE;