USE BOOK1;
-- 1:1
CREATE TABLE STUDENT(
STUDENT_ID INT PRIMARY KEY,
STUDENT_NAME VARCHAR(67)
);
CREATE TABLE DETAILS(
ID INT,
STUDENT_AGE INT,
FOREIGN KEY (ID) REFERENCES STUDENT(STUDENT_ID)
);
INSERT INTO STUDENT VALUES(1,"AMMU"),(2,"JETTI"),(3,"APPLE");
SELECT* FROM STUDENT;
INSERT INTO DETAILS VALUES(1,23),(2,22),(3,21);
SELECT* FROM DETAILS;

-- 1:M
CREATE TABLE STUDENT01(
STUDENT01_ID INT PRIMARY KEY,
STUDENT_NAME VARCHAR(56)
);
CREATE TABLE COURSE01(
ID INT,
COURSE_NAME VARCHAR(56),
FOREIGN KEY (ID) REFERENCES STUDENT01(STUDENT01_ID)
);
INSERT INTO STUDENT01 VALUES(1,"NANDU"),(2,"APPLE"),(3,"JYOSH");
INSERT INTO COURSE01 VALUES(1,"PYTHON"),(2,"JAVA"),(3,"SAP");
SELECT* FROM STUDENT01;
SELECT*FROM COURSE01;

